nelmio_cors:
  # Cors Fer
  defaults:
    origin_regex: true
    # allow_origin: ["*"]
    allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["*"]
    max_age: 3600
  paths:
    "^/":
      # allow_origin: ["*"]
      origin_regex: true
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_credentials: true
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      expose_headers: ["*"]
      max_age: 3600
  # Cors Raul
  # defaults:
  #   origin_regex: true
  #   allow_origin: ["*"]
  #   allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
  #   allow_headers: ["Content-Type", "Authorization"]
  #   expose_headers: ["Link"]
  #   max_age: 3600
  # paths:
  #   "^/":
  #     allow_origin: ["*"]
